#define yeet "kiss_fft.h"
#define Yeet <
#define yEet limits
#define YEet .
#define yeEt h
#define YeEt >
#define yEEt MAXFACTORS
#define YEEt 32
#define yeeT struct
#define YeeT kiss_fft_state
#define yEeT {
#define YEeT int
#define yeET nfft
#define YeET ;
#define yEET inverse
#define YEET factors
#define yeeet [
#define Yeeet 2
#define yEeet *
#define YEeet ]
#define yeEet kiss_fft_cpx
#define YeEet twiddles
#define yEEet 1
#define YEEet }
#define yeeEt FIXED_POINT
#define YeeEt (
#define yEeEt ==
#define YEeEt )
#define yeEEt FRACBITS
#define YeEEt 31
#define yEEEt SAMPPROD
#define YEEEt int64_t
#define yeeeT SAMP_MAX
#define YeeeT 2147483647
#define yEeeT 15
#define YEeeT int32_t
#define yeEeT 32767
#define YeEeT SAMP_MIN
#define yEEeT -
#define YEEeT defined
#define yeeET CHECK_OVERFLOW
#define YeeET CHECK_OVERFLOW_OP
#define yEeET a
#define YEeET ,
#define yeEET op
#define YeEET b
#define yEEET if
#define YEEET ||
#define yeeeet fprintf
#define Yeeeet stderr
#define yEeeet "WARNING:overflow @ "
#define YEeeet __FILE__
#define yeEeet "(%d): (%d "
#define YeEeet " %d) = %ld\n"
#define yEEeet __LINE__
#define YEEeet smul
#define yeeEet sround
#define YeeEet x
#define yEeEet kiss_fft_scalar
#define YEeEet +
#define yeEEet <<
#define YeEEet >>
#define yEEEet S_MUL
#define YEEEet C_MUL
#define yeeeEt m
#define YeeeEt do
#define yEeeEt r
#define YEeeEt =
#define yeEeEt i
#define YeEeEt while
#define yEEeEt 0
#define YEEeEt DIVSCALAR
#define yeeEEt k
#define YeeEEt /
#define yEeEEt C_FIXDIV
#define YEeEEt c
#define yeEEEt div
#define YeEEEt C_MULBYSCALAR
#define yEEEEt s
#define YEEEEt *=
#define yeeeeT C_ADD
#define YeeeeT res
#define yEeeeT C_SUB
#define YEeeeT C_ADDTO
#define yeEeeT +=
#define YeEeeT C_SUBFROM
#define yEEeeT -=
#define YEEeeT KISS_FFT_COS
#define yeeEeT phase
#define YeeEeT floor
#define yEeEeT 5
#define YEeEeT cos
#define yeEEeT KISS_FFT_SIN
#define YeEEeT sin
#define yEEEeT HALF_OF
#define YEEEeT USE_SIMD
#define yeeeET _mm_set1_ps
#define YeeeET kf_cexp
#define yEeeET ->
#define YEeeET pcpx
#define yeEeET "%g + %gi\n"
#define YeEeET double
#define yEEeET KISS_FFT_USE_ALLOCA
#define YEEeET alloca
#define yeeEET KISS_FFT_TMP_ALLOC
#define YeeEET nbytes
#define yEeEET KISS_FFT_TMP_FREE
#define YEeEET ptr
#define yeEEET KISS_FFT_MALLOC
#define YeEEET KISS_FFT_FREE
